#!/bin/bash
sudo apt install -y telnet
sudo apt install -y nginx
sudo systemctl enable nginx
sudo chmod -R 755 /var/www/html
sudo mkdir -p /var/www/html/app1
HOSTNAME=$(hostname)
sudo echo "<html> <link rel='stylesheet' href='https://www.gstatic.com/dialogflow-console/fast/df-messenger/prod/v1/themes/df-messenger-default.css'> <script src='https://www.gstatic.com/dialogflow-console/fast/df-messenger/prod/v1/df-messenger.js'></script> <df-messenger project-id='tcs-llm' agent-id='ecf871cc-91b9-470d-ba62-f2df5a82cb1f' language-code='en' max-query-length='-1'> <df-messenger-chat-bubble chat-title='tcs-bot'> </df-messenger-chat-bubble> </df-messenger> <style> df-messenger { z-index: 999; position: fixed; --df-messenger-font-color: #000; --df-messenger-font-family: Google Sans; --df-messenger-chat-background: #f3f6fc; --df-messenger-message-user-background: #d3e3fd; --df-messenger-message-bot-background: #fff; bottom: 16px; right: 16px; } </style> <body> <h3>Welcome to TCS - chatbot demo</h3> </body> </html>" | sudo tee /var/www/html/app1/index.html
sudo echo "<html> <link rel='stylesheet' href='https://www.gstatic.com/dialogflow-console/fast/df-messenger/prod/v1/themes/df-messenger-default.css'> <script src='https://www.gstatic.com/dialogflow-console/fast/df-messenger/prod/v1/df-messenger.js'></script> <df-messenger project-id='tcs-llm' agent-id='ecf871cc-91b9-470d-ba62-f2df5a82cb1f' language-code='en' max-query-length='-1'> <df-messenger-chat-bubble chat-title='tcs-bot'> </df-messenger-chat-bubble> </df-messenger> <style> df-messenger { z-index: 999; position: fixed; --df-messenger-font-color: #000; --df-messenger-font-family: Google Sans; --df-messenger-chat-background: #f3f6fc; --df-messenger-message-user-background: #d3e3fd; --df-messenger-message-bot-background: #fff; bottom: 16px; right: 16px; } </style> <body> <h3>Welcome to TCS - chatbot demo</h3> </body> </html>" | sudo tee /var/www/html/index.html
